Repository InformedSolutions/JAQU-CAZ-Notify-Gateway, pull requests merged in 2021-02, with the labels that each got.

#67 [CAZB-4063] Upgrade Terraform version in pipeline
  .drone.yml
  .drone2.yml
Labels: bug

#68 [CAZB-4051] Add polling iterations to Notify Gateway
  src/main/java/uk/gov/caz/notify/service/MessageHandlingService.java
  src/main/resources/application.yml
  src/test/java/uk/gov/caz/notify/service/MessageHandlingServiceTest.java
Labels: bug, enhancement

#70 Promote Notify v1.2.0 to Pre-Prod
  .drone2.yml
  documentation-assets/C4L4.png
  documentation-assets/C4L4.uml
  pom.xml
  src/main/java/uk/gov/caz/notify/domain/QueueName.java
  src/main/java/uk/gov/caz/notify/messaging/MessagingClient.java
  src/main/java/uk/gov/caz/notify/service/MessageHandlingService.java
  src/test/java/uk/gov/caz/notify/controller/ManualDispatchControllerTest.java
  src/test/java/uk/gov/caz/notify/messaging/MessagingClientTest.java
  src/test/java/uk/gov/caz/notify/service/MessageHandlingServiceTest.java
Labels: Notify v1.2.0, release
